version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    ports:
      - "5431:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
